# Generated by Django 2.1.2 on 2018-11-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=200)),
                ('good_type', models.CharField(choices=[('mono', 'Монобукеты'), ('birthday', 'День Рождения'), ('hat_boxes', 'Шляпные коробки'), ('modern', 'Современные букеты'), ('love', 'Любовь'), ('men', 'Мужчинам')], default='love', max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='дата опубликования')),
            ],
        ),
    ]
