# Generated by Django 2.1.2 on 2018-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='id',
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
