# Generated by Django 2.1.2 on 2018-12-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_goods_good_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_name',
            new_name='goods_name',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_photo',
            new_name='goods_photo',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_type',
            new_name='goods_type',
        ),
    ]
