# Generated by Django 2.1.2 on 2018-12-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0004_auto_20181203_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=200),
        ),
    ]
