# Generated by Django 2.1.2 on 2018-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0005_auto_20181204_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
