# Generated by Django 2.1.2 on 2018-12-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0006_auto_20181204_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo_checked',
            field=models.BooleanField(default=False),
        ),
    ]
