# Generated by Django 2.1.2 on 2018-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0007_goods_photo_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
